### ISSUE TITLE
Can't load Nvim-R options and find completion files

### ISSUE THREAD

**Issue by c1au6i0** [gaalcaras/ncm-R#35]
Hello I am using `NeoVim`, I have `Nvim-R` plug installed and operational but I get this error when using `ncmR` .

```
[ncmR] Can't load Nvim-R options. Did you install the Nvim-R plugin?
[ncmR] Can't find completion files. Please load the R packages you need (e.g. "base" or "utils").
[ncm_r@yarp] Traceback (most recent call last):
[ncm_r@yarp]   File "/home/clz4002/.vim/plugged/nvim-yarp/pythonx/yarp.py", line 63, in <module>
[ncm_r@yarp]     module_obj = importlib.import_module(module)
[ncm_r@yarp]   File "/home/clz4002/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
[ncm_r@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[ncm_r@yarp]   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm_r@yarp]   File "/home/clz4002/.vim/plugged/ncm-R/pythonx/ncm_r.py", line 303, in <module>
[ncm_r@yarp]     SOURCE = Source(vim)
[ncm_r@yarp]   File "/home/clz4002/.vim/plugged/ncm-R/pythonx/ncm_r.py", line 37, in __init__
[ncm_r@yarp]     self.get_all_pkg_matches()
[ncm_r@yarp]   File "/home/clz4002/.vim/plugged/ncm-R/pythonx/ncm_r.py", line 128, in get_all_pkg_matches
[ncm_r@yarp]     comps = [f for f in listdir(cmp) if 'omnils' in f]
[ncm_r@yarp] FileNotFoundError: [Errno 2] No such file or directory: ''
[ncm_r@yarp] Job is dead. cmd=['/home/clz4002/miniconda3/bin/python3', '-u', '/home/clz4002/.vim/plugged/nvim-yarp/pythonx/yarp.py', '/scratch/clz4002_238755/nvimR3Gyqd/0', 5, 'ncm_r']
```
Completion works for non R libraries and previously used commands.
I looked for "g:rplugin_compldir" as indicated in a previous issue but I did not find it on my system.

Thanks!

**Comment by oli666** [comment]
Same issue here

**Comment by Bartosz1280** [comment]
Have completely the same issue. The problem seems to be independent of other plugs and custom configurations.

**Comment by luizpara** [comment]
Not that I hope anyone is still paying attention, but same here.

**Comment by usrbinr** [comment]
same issue here --- starting with a fresh init file and still have the issue.
